server { 
  listen 80;
  server_name .clipdx.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name .clipdx.com;
  # Location chosen in Dockerfile
  ssl_certificate /etc/letsencrypt/clipdx.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/clipdx.com/privkey.pem;
  location / {
    root /usr/share/nginx/html;
    # Untested: $uri.html $uri/index.html idea
    # to capture e.g. /webday -> webday.html or /webday -> /webday/index.html ?
    try_files $uri $uri.html $uri/index.html /index.html;
    index /index.html;
  }
}
